var multiChoiceConfig = {
  // TODO: Maybe we don't need the name here?
  data: {
    "产品类型": [
      {name: 'productAbroadGroup', value: '出境跟团游'},
      {name: 'productAbroadFreedom', value: '出境自由行'},
      {name: 'productDomesticGroup', value: '国内跟团游'},
      {name: 'productDomesticFreedom', value: '国内自由行'},
      {name: 'productDomresticNearby', value: '国内周边游'},
      {name: 'productVisaService', value: '签证服务'},
    ],
    "经营范围": [
      {name: 'providerDeparture', value: '出境旅游'},
      {name: 'providerArrival', value: '入境旅游'},
      {name: 'providerDomestic', value: '境内旅游'},
      {name: 'providerTicketDelegate', value: '票务代理'},
      {name: 'providerBookhotel', value: '住宿'},
    ],
    "主营目的地": [
      {name: "ouzhou", value: '欧洲'},
      {name: "meizhou", value: '美洲'},
      {name: 'aouzhou', value: '澳洲'},
      {name: 'dayangzhou', value: '大洋洲'},
      {name: 'dongnanya', value: '东南亚'},
      {name: 'youlun', value: '邮轮'},
      {name: 'haidao', value: '海岛'},
      {name: 'riben', value: '日韩'},
      {name: 'guoneichangxian', value: '国内长线'},
      {name: 'guoneizhoubian', value: '周边短线'},
      {name: 'ziyouxing', value: '自由行'},
      {name: 'zijiayou', value: '自驾游'},
      {name: 'gangaotai', value: '港澳台'},

    ],
    "主营口岸": [
      {name: 'shanghai', value: '上海'},
      {name: 'beijing', value: '北京'},
      {name: 'tianjin', value: '天津'},
      {name: 'hangzhou', value: '杭州'},
    ],
    //春节，国庆，元旦，暑期，寒假，端午，中秋，家庭游，亲子游，闺蜜游，错峰游，多人立减，早定特惠，周末游，自驾游，自由行，蜜月游，漂流，古镇游，温泉
    "线路前缀": [
      {name: 'duanwu', value: '端午'},
      {name: 'shuqi', value: '暑期'},
      {name: 'cuofengyou', value: '错峰游'},
      {name: 'duorenlijian', value: '多人立减'},
      {name: 'zaodinglijian', value: '早定特惠'},
      {name: 'chunjie', value: "春节"},
      {name: 'guoqing', value: "国庆"},
      {name: 'yuandan', value: "元旦"},
      {name: 'shujia', value: "暑假"},
      {name: "hanjia", value: "寒假"},
      {name: "zhongqiu", value: "中秋"},
      {name: "jiatingyou", value: "家庭游"},
      {name: 'qinziyou', value: '亲子游'},
      {name: 'guimiyou', value: '闺蜜游' },
      {name: 'zhoumoyou', value: '周末游' },
      {name: 'ziyouxing', value: '自由行' },
      {name: 'zijiayou', value: '自驾游' },
      {name: 'miyueyou', value: '蜜月游' },
      {name: 'piaoliu', value: '漂流' },
      {name: 'guzhenyou', value: '古镇游' },
      {name: 'wenquan', value: '温泉' },
    ],
    "东南亚": [
      {name: "泰国", value: "泰国"},
      {name: "曼谷+芭提雅", value: "曼谷+芭提雅"},
      {name: "曼谷+芭提雅+普吉岛", value: "曼谷+芭提雅+普吉岛"},
      {name: "普吉岛", value: "普吉岛"},
      {name: "甲米", value: "甲米"},
      {name: "清迈", value: "清迈"},
      {name: "甲米+清迈", value: "甲米+清迈"},
      {name: "斯米兰岛", value: "斯米兰岛"},
      {name: "苏梅岛", value: "苏梅岛"},
      {name: "柬埔寨", value: "柬埔寨"},
      {name: "柬埔寨+越南", value: "柬埔寨+越南"},
      {name: "越南", value: "越南"},
      {name: "芽庄", value: "芽庄"},
      {name: "岘港", value: "岘港"},
      {name: "老挝", value: "老挝"},
      {name: "菲律宾", value: "菲律宾"},
      {name: "宿雾", value: "宿雾"},
      {name: "长滩", value: "长滩"},
      {name: "巴厘岛", value: "巴厘岛"},
      {name: "兰卡威", value: "兰卡威"},
      {name: "新加坡", value: "新加坡"},
      {name: "沙巴", value: "沙巴"},
      {name: "马来西亚", value: "马来西亚"},
    ],
    "日本": [
      {name: "本州", value: "本州"},
      {name: "冲绳", value: "冲绳"},
      {name: "东京+大阪+京都", value: "东京+大阪+京都"},
      {name: "北海道", value: "北海道"},
      {name: "名古屋", value: "名古屋"},
      {name: "东京+北海道", value: "东京+北海道"},
      {name: "东京+箱根", value: "东京+箱根"},
      {name: "九州", value: "九州"},
      {name: "鹿儿岛", value: "鹿儿岛"},
    ],
    "韩国": [
      {name: "首尔", value: "首尔"},
      {name: "济州", value: "济州"},
      {name: "清州+大邱+首尔", value: "清州+大邱+首尔"},
      {name: "釜山", value: "釜山"},
      {name: "江原道", value: "江原道"},
      {name: "首尔+济州", value: "首尔+济州"},
    ],
    "海岛": [
      {name: "普吉岛", value: "普吉岛"},
      {name: "夏威夷", value: "夏威夷"},
      {name: "塞班", value: "塞班"},
      {name: "沙巴", value: "沙巴"},
      {name: "岘港", value: "岘港"},
      {name: "马尔代夫", value: "马尔代夫"},
      {name: "塞舌尔", value: "塞舌尔"},
      {name: "毛里求斯", value: "毛里求斯"},
      {name: "斯里兰卡", value: "斯里兰卡"},
      {name: "巴厘岛", value: "巴厘岛"},
      {name: "苏梅岛", value: "苏梅岛"},
      {name: "大溪地", value: "大溪地"},
      {name: "长滩岛", value: "长滩岛"},
      {name: "斐济", value: "斐济"},
      {name: "关岛", value: "关岛"},
      {name: "普吉岛", value: "普吉岛"},
    ],
    "欧洲": [
      {name: "法国", value: "法国"},
      {name: "意大利", value: "意大利"},
      {name: "俄罗斯", value: "俄罗斯"},
      {name: "瑞士", value: "瑞士"},
      {name: "德国", value: "德国"},
      {name: "东欧", value: "东欧"},
      {name: "英国", value: "英国"},
      {name: "荷兰", value: "荷兰"},
      {name: "奥地利", value: "奥地利"},
      {name: "西班牙+葡萄牙", value: "西班牙+葡萄牙"},
      {name: "北欧", value: "北欧"},
      {name: "希腊", value: "希腊"},
      {name: "冰岛", value: "冰岛"},
      {name: "法意瑞", value: "法意瑞"},
    ],
    "澳新": [
      {name: "澳大利亚", value: "澳大利亚"},
      {name: "悉尼", value: "悉尼"},
      {name: "新西兰", value: "新西兰"},
      {name: "大堡礁", value: "大堡礁"},
      {name: "澳大利亚+新西兰", value: "澳大利亚+新西兰"},
      {name: "皇后镇", value: "皇后镇"},
      {name: "奥克兰", value: "奥克兰"},
      {name: "基督城", value: "基督城"},
    ],
    "美洲": [
      {name: "美国", value: "美国"},
      {name: "加拿大", value: "加拿大"},
      {name: "巴西", value: "巴西"},
      {name: "阿根廷", value: "阿根廷"},
      {name: "墨西哥", value: "墨西哥"},
      {name: "夏威夷", value: "夏威夷"},
      {name: "关岛", value: "关岛"},
      {name: "纽约", value: "纽约"},
      {name: "洛杉矶", value: "洛杉矶"},
      {name: "拉斯维加斯", value: "拉斯维加斯"},
      {name: "旧金山", value: "旧金山"},
      {name: "华盛顿", value: "华盛顿"},
      {name: "温哥华", value: "温哥华"},
    ],
    "中东非": [
      {name: "阿联酋", value: "阿联酋"},
      {name: "迪拜", value: "迪拜"},
      {name: "埃及", value: "埃及"},
      {name: "肯尼亚", value: "肯尼亚"},
      {name: "南非", value: "南非"},
      {name: "坦桑尼亚", value: "坦桑尼亚"},
      {name: "摩洛哥", value: "摩洛哥"},
      {name: "以色列", value: "以色列"},
      {name: "毛里求斯", value: "毛里求斯"},
      {name: "埃塞俄比亚塞舌尔", value: "埃塞俄比亚塞舌尔"},
      {name: "突尼斯", value: "突尼斯"},
      {name: "约旦", value: "约旦"},
      {name: "伊朗", value: "伊朗"},
      {name: "土耳其", value: "土耳其"},
    ],
    "海南": [
      {name: "三亚", value: "三亚"},
      {name: "海口", value: "海口"},
    ],
    "云南": [
      {name: "丽江", value: "丽江"},
      {name: "昆明", value: "昆明"},
      {name: "香格里拉", value: "香格里拉"},
      {name: "西双版纳", value: "西双版纳"},
      {name: "泸沽湖", value: "泸沽湖"},
    ],
    "湖南": [
      {name: "张家界", value: "张家界"},
      {name: "长沙", value: "长沙"},
      {name: "韶山", value: "韶山"},
    ],
    "四川": [
      {name: "九寨沟", value: "九寨沟"},
      {name: "成都", value: "成都"},
      {name: "峨眉山", value: "峨眉山"},
      {name: "乐山", value: "乐山"},
      {name: "青城山", value: "青城山"},
      {name: "海螺沟", value: "海螺沟"},
      {name: "都江堰", value: "都江堰"},
      {name: "丹巴", value: "丹巴"},
      {name: "稻城亚丁", value: "稻城亚丁"},
      {name: "若尔盖", value: "若尔盖"},
    ],
    "广西": [
      {name: "桂林", value: "桂林"},
      {name: "北海", value: "北海"},
      {name: "南宁", value: "南宁"},
      {name: "阳朔", value: "阳朔"},
      {name: "涠洲岛", value: "涠洲岛"},
    ],
    "福建": [
      {name: "厦门", value: "厦门"},
      {name: "福州", value: "福州"},
      {name: "鼓浪屿", value: "鼓浪屿"},
      {name: "永定土楼", value: "永定土楼"},
      {name: "武夷山", value: "武夷山"},
    ],
    "贵州": [
      {name: "黄果树瀑布", value: "黄果树瀑布"},
      {name: "贵阳", value: "贵阳"},
      {name: "遵义", value: "遵义"},
    ],
    "西北": [
      {name: "敦煌", value: "敦煌"},
      {name: "兰州", value: "兰州"},
      {name: "西宁", value: "西宁"},
      {name: "青海湖", value: "青海湖"},
      {name: "银川", value: "银川"},
      {name: "中卫", value: "中卫"},
      {name: "莫高窟", value: "莫高窟"},
    ],
    "新疆": [
      {name: "吐鲁番", value: "吐鲁番"},
      {name: "天山天池", value: "天山天池"},
      {name: "乌鲁木齐", value: "乌鲁木齐"},
    ],
    "内蒙": [
      {name: "海拉尔", value: "海拉尔"},
      {name: "呼伦贝尔", value: "呼伦贝尔"},
      {name: "呼和浩特", value: "呼和浩特"},
      {name: "鄂尔多斯", value: "鄂尔多斯"},
      {name: "满洲里", value: "满洲里"},
    ],
    "陕西": [
      {name: "西安", value: "西安"},
      {name: "延安", value: "延安"},
      {name: "华山", value: "华山"},
      {name: "壶口瀑布", value: "壶口瀑布"},
    ],
    "西藏": [
      {name: "拉萨", value: "拉萨"},
      {name: "林芝", value: "林芝"},
    ],
    "湖北": [
      {name: "三峡", value: "三峡"},
      {name: "武汉", value: "武汉"},
      {name: "武当山", value: "武当山"},
      {name: "神农架", value: "神农架"},
      {name: "恩施", value: "恩施"},
    ],
    "重庆": [
      {name: "长江三峡", value: "长江三峡"},
      {name: "武隆", value: "武隆"},
    ],
    "山东": [
      {name: "青岛", value: "青岛"},
      {name: "烟台", value: "烟台"},
      {name: "威海", value: "威海"},
      {name: "济南", value: "济南"},
      {name: "泰山", value: "泰山"},
      {name: "日照", value: "日照"},
      {name: "曲阜", value: "曲阜"},
      {name: "蓬莱", value: "蓬莱"},
    ],
    "东北": [
      {name: "长白山", value: "长白山"},
      {name: "金石滩", value: "金石滩"},
      {name: "大连", value: "大连"},
      {name: "哈尔滨", value: "哈尔滨"},
      {name: "吉林", value: "吉林"},
      {name: "中国雪乡", value: "中国雪乡"},
      {name: "亚布力滑雪", value: "亚布力滑雪"},
      {name: "天池", value: "天池"},
    ],
    "山西": [
      {name: "五台山", value: "五台山"},
      {name: "太原", value: "太原"},
      {name: "平遥古城", value: "平遥古城"},
      {name: "云冈石窟", value: "云冈石窟"},
      {name: "大同", value: "大同"},
      {name: "乔家大院", value: "乔家大院"},
    ],
    "河南": [
      {name: "洛阳", value: "洛阳"},
      {name: "郑州", value: "郑州"},
      {name: "开封", value: "开封"},
      {name: "少林寺", value: "少林寺"},
      {name: "云台山", value: "云台山"},
      {name: "安阳", value: "安阳"},
      {name: "郭亮村", value: "郭亮村"},
    ],
    "都市名城": [
      {name: "杭州", value: "杭州"},
      {name: "南京", value: "南京"},
      {name: "苏州", value: "苏州"},
      {name: "宁波", value: "宁波"},
      {name: "无锡", value: "无锡"},
      {name: "常州", value: "常州"},
      {name: "景德镇", value: "景德镇"},
      {name: "泰州", value: "泰州"},
      {name: "奉化", value: "奉化"},
      {name: "镇江", value: "镇江"},
      {name: "横店", value: "横店"},
      {name: "扬州", value: "扬州"},
      {name: "上海", value: "上海"},
      {name: "合肥", value: "合肥"},
      {name: "浙江", value: "浙江"},
      {name: "江苏", value: "江苏"},
      {name: "江西", value: "江西"},
      {name: "安徽", value: "安徽"},
      {name: "上海", value: "上海"},
    ],
    "古镇水乡": [
      {name: "乌镇", value: "乌镇"},
      {name: "磐安", value: "磐安"},
      {name: "安吉", value: "安吉"},
      {name: "蛇蟠岛", value: "蛇蟠岛"},
      {name: "西塘", value: "西塘"},
      {name: "桐庐", value: "桐庐"},
      {name: "象山", value: "象山"},
      {name: "仙都", value: "仙都"},
      {name: "周庄", value: "周庄"},
      {name: "临安", value: "临安"},
      {name: "石浦", value: "石浦"},
      {name: "同里婺源", value: "同里婺源"},
      {name: "舟山", value: "舟山"},
    ],
    "名山大川": [
      {name: "大明山", value: "大明山"},
      {name: "九华山", value: "九华山"},
      {name: "华山", value: "华山"},
      {name: "三清山", value: "三清山"},
      {name: "雁荡山", value: "雁荡山"},
      {name: "普陀山", value: "普陀山"},
      {name: "千岛湖", value: "千岛湖"},
      {name: "三山岛", value: "三山岛"},
      {name: "龙虎山", value: "龙虎山"},
      {name: "黄山", value: "黄山"},
      {name: "庐山", value: "庐山"},
      {name: "天目山", value: "天目山"},
      {name: "齐云山", value: "齐云山"},
      {name: "天柱山", value: "天柱山"},
    ],
  }
};

export default multiChoiceConfig;
